

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findglog.cmake")
# Global approach
set(glog_FOUND 1)
set(glog_VERSION "0.4.0")

find_package_handle_standard_args(glog REQUIRED_VARS
                                  glog_VERSION VERSION_VAR glog_VERSION)
mark_as_advanced(glog_FOUND glog_VERSION)


set(glog_INCLUDE_DIRS "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/include")
set(glog_INCLUDE_DIR "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/include")
set(glog_INCLUDES "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/include")
set(glog_RES_DIRS )
set(glog_DEFINITIONS "-DGFLAGS_DLL_DECLARE_FLAG="
			"-DGFLAGS_DLL_DEFINE_FLAG=")
set(glog_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(glog_COMPILE_DEFINITIONS "GFLAGS_DLL_DECLARE_FLAG="
			"GFLAGS_DLL_DEFINE_FLAG=")
set(glog_COMPILE_OPTIONS_LIST "" "")
set(glog_COMPILE_OPTIONS_C "")
set(glog_COMPILE_OPTIONS_CXX "")
set(glog_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(glog_LIBRARIES "") # Will be filled later
set(glog_LIBS "") # Same as glog_LIBRARIES
set(glog_SYSTEM_LIBS pthread)
set(glog_FRAMEWORK_DIRS )
set(glog_FRAMEWORKS )
set(glog_FRAMEWORKS_FOUND "") # Will be filled later
set(glog_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(glog_FRAMEWORKS_FOUND "${glog_FRAMEWORKS}" "${glog_FRAMEWORK_DIRS}")

mark_as_advanced(glog_INCLUDE_DIRS
                 glog_INCLUDE_DIR
                 glog_INCLUDES
                 glog_DEFINITIONS
                 glog_LINKER_FLAGS_LIST
                 glog_COMPILE_DEFINITIONS
                 glog_COMPILE_OPTIONS_LIST
                 glog_LIBRARIES
                 glog_LIBS
                 glog_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to glog_LIBS and glog_LIBRARY_LIST
set(glog_LIBRARY_LIST glog)
set(glog_LIB_DIRS "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_glog_DEPENDENCIES "${glog_FRAMEWORKS_FOUND} ${glog_SYSTEM_LIBS} gflags::gflags")

conan_package_library_targets("${glog_LIBRARY_LIST}"  # libraries
                              "${glog_LIB_DIRS}"      # package_libdir
                              "${_glog_DEPENDENCIES}"  # deps
                              glog_LIBRARIES            # out_libraries
                              glog_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "glog")                                      # package_name

set(glog_LIBS ${glog_LIBRARIES})

foreach(_FRAMEWORK ${glog_FRAMEWORKS_FOUND})
    list(APPEND glog_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND glog_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${glog_SYSTEM_LIBS})
    list(APPEND glog_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND glog_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(glog_LIBRARIES_TARGETS "${glog_LIBRARIES_TARGETS};gflags::gflags")
set(glog_LIBRARIES "${glog_LIBRARIES};gflags::gflags")

set(CMAKE_MODULE_PATH "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/sumeet/.conan/data/glog/0.4.0/_/_/package/cc4e1230d0b57d9c08afdb6905dc49ef97ce1b00/" ${CMAKE_PREFIX_PATH})

foreach(_BUILD_MODULE_PATH ${glog_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET glog::glog)
        add_library(glog::glog INTERFACE IMPORTED)
        if(glog_INCLUDE_DIRS)
            set_target_properties(glog::glog PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${glog_INCLUDE_DIRS}")
        endif()
        set_property(TARGET glog::glog PROPERTY INTERFACE_LINK_LIBRARIES
                     "${glog_LIBRARIES_TARGETS};${glog_LINKER_FLAGS_LIST}")
        set_property(TARGET glog::glog PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${glog_COMPILE_DEFINITIONS})
        set_property(TARGET glog::glog PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${glog_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT gflags_FOUND)
            find_dependency(gflags REQUIRED)
        else()
            message(STATUS "Dependency gflags already found")
        endif()

    endif()
endif()
