

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findgflags.cmake")
# Global approach
set(gflags_FOUND 1)
set(gflags_VERSION "2.2.2")

find_package_handle_standard_args(gflags REQUIRED_VARS
                                  gflags_VERSION VERSION_VAR gflags_VERSION)
mark_as_advanced(gflags_FOUND gflags_VERSION)


set(gflags_INCLUDE_DIRS "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/include")
set(gflags_INCLUDE_DIR "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/include")
set(gflags_INCLUDES "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/include")
set(gflags_RES_DIRS )
set(gflags_DEFINITIONS )
set(gflags_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(gflags_COMPILE_DEFINITIONS )
set(gflags_COMPILE_OPTIONS_LIST "" "")
set(gflags_COMPILE_OPTIONS_C "")
set(gflags_COMPILE_OPTIONS_CXX "")
set(gflags_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(gflags_LIBRARIES "") # Will be filled later
set(gflags_LIBS "") # Same as gflags_LIBRARIES
set(gflags_SYSTEM_LIBS )
set(gflags_FRAMEWORK_DIRS )
set(gflags_FRAMEWORKS )
set(gflags_FRAMEWORKS_FOUND "") # Will be filled later
set(gflags_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(gflags_FRAMEWORKS_FOUND "${gflags_FRAMEWORKS}" "${gflags_FRAMEWORK_DIRS}")

mark_as_advanced(gflags_INCLUDE_DIRS
                 gflags_INCLUDE_DIR
                 gflags_INCLUDES
                 gflags_DEFINITIONS
                 gflags_LINKER_FLAGS_LIST
                 gflags_COMPILE_DEFINITIONS
                 gflags_COMPILE_OPTIONS_LIST
                 gflags_LIBRARIES
                 gflags_LIBS
                 gflags_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to gflags_LIBS and gflags_LIBRARY_LIST
set(gflags_LIBRARY_LIST gflags_nothreads pthread m)
set(gflags_LIB_DIRS "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_gflags_DEPENDENCIES "${gflags_FRAMEWORKS_FOUND} ${gflags_SYSTEM_LIBS} ")

conan_package_library_targets("${gflags_LIBRARY_LIST}"  # libraries
                              "${gflags_LIB_DIRS}"      # package_libdir
                              "${_gflags_DEPENDENCIES}"  # deps
                              gflags_LIBRARIES            # out_libraries
                              gflags_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "gflags")                                      # package_name

set(gflags_LIBS ${gflags_LIBRARIES})

foreach(_FRAMEWORK ${gflags_FRAMEWORKS_FOUND})
    list(APPEND gflags_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND gflags_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${gflags_SYSTEM_LIBS})
    list(APPEND gflags_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND gflags_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(gflags_LIBRARIES_TARGETS "${gflags_LIBRARIES_TARGETS};")
set(gflags_LIBRARIES "${gflags_LIBRARIES};")

set(CMAKE_MODULE_PATH "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/sumeet/.conan/data/gflags/2.2.2/_/_/package/00c98caa4d6671605623f39dba94f8a482c5f538/" ${CMAKE_PREFIX_PATH})

foreach(_BUILD_MODULE_PATH ${gflags_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET gflags::gflags)
        add_library(gflags::gflags INTERFACE IMPORTED)
        if(gflags_INCLUDE_DIRS)
            set_target_properties(gflags::gflags PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${gflags_INCLUDE_DIRS}")
        endif()
        set_property(TARGET gflags::gflags PROPERTY INTERFACE_LINK_LIBRARIES
                     "${gflags_LIBRARIES_TARGETS};${gflags_LINKER_FLAGS_LIST}")
        set_property(TARGET gflags::gflags PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${gflags_COMPILE_DEFINITIONS})
        set_property(TARGET gflags::gflags PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${gflags_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()
